### ISSUE TITLE
无法正常拉取代码

### ISSUE THREAD

**Issue by missmimia** [bmpi-dev/logseq.xyz#4]
pull代码的时候提示没有在对应仓库安装logseq-xyz，但是github看是正常安装了的。

<img width="955" alt="image" src="https://user-images.githubusercontent.com/28520397/153382197-0b1b1f86-2b6e-47a3-a01b-5109ab33bf1b.png">

卸载重新绑定也还是不行，是哪里出了问题吗？
之前是正常的。

**Comment by madawei2699** [comment]
今天我也遇到这个问题了，看日志是后端与GitHub集成出了问题，可能是GitHub做了更新导致的，我还在看这个问题

**Comment by madawei2699** [comment]
@missmimia 服务正常了，是CORS服务挂了导致的
